import { Category, FeaturedTool, ValueProp } from "@/types";

export const ROADMAP_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Developer Tools",
    slug: "developer-tools",
    description: "Formatters, decoders, minifiers, SVG tools, and essential coding utilities.",
    iconName: "Code2",
    color: "from-zinc-800 to-zinc-900 text-sky-400 border-zinc-700/60",
    toolCount: 3,
  },
  {
    id: "cat-2",
    name: "Security & Crypto",
    slug: "security",
    description: "Strong password generators, digital signature tools, and token validators.",
    iconName: "ShieldCheck",
    color: "from-zinc-800 to-zinc-900 text-emerald-400 border-zinc-700/60",
    toolCount: 2,
  },
  {
    id: "cat-3",
    name: "Text & Markdown",
    slug: "text-utilities",
    description: "Markdown editors, document converters, Base64 encoders, and text formatters.",
    iconName: "Binary",
    color: "from-zinc-800 to-zinc-900 text-violet-400 border-zinc-700/60",
    toolCount: 3,
  },
  {
    id: "cat-4",
    name: "CSS & UI Utilities",
    slug: "css-ui",
    description: "QR code generators, barcode generators, color palettes, and SVG icon suites.",
    iconName: "Palette",
    color: "from-zinc-800 to-zinc-900 text-amber-400 border-zinc-700/60",
    toolCount: 4,
  },
  {
    id: "cat-5",
    name: "Image & Asset Tools",
    slug: "image-tools",
    description: "ImaGrow image editor, image processor, favicon converter, and video to GIF.",
    iconName: "Image",
    color: "from-zinc-800 to-zinc-900 text-rose-400 border-zinc-700/60",
    toolCount: 4,
  },
  {
    id: "cat-6",
    name: "PDF Utilities",
    slug: "pdf-tools",
    description: "Merge, split, compress, page numberer, and N-up grid page layout.",
    iconName: "FileText",
    color: "from-zinc-800 to-zinc-900 text-indigo-400 border-zinc-700/60",
    toolCount: 5,
  },
  {
    id: "cat-7",
    name: "Generators & Media",
    slug: "ai-tools",
    description: "AI Flowchart generator, invoice builder, and audio format converter.",
    iconName: "Sparkles",
    color: "from-zinc-800 to-zinc-900 text-teal-400 border-zinc-700/60",
    toolCount: 3,
  },
];

export const FEATURED_TOOLS: FeaturedTool[] = [
  {
    id: "tool-1",
    name: "SVG Icons Library",
    slug: "svg-icons-library",
    tagline: "Searchable SVG icon library with instant search, pack filters, stroke/color customization, and JSX/React copy.",
    categorySlug: "css-ui",
    categoryName: "CSS & UI Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "svg-icons-library",
    popular: true,
    iconName: "Palette",
    gradient: "from-amber-500 to-orange-600",
    tags: ["Icons", "SVG", "JSX", "React", "UI"],
  },
  {
    id: "tool-2",
    name: "Color Palette Generator",
    slug: "color-palette-generator",
    tagline: "Generate and browse color palettes with harmony modes (monochrome, triadic, complementary) and contrast checker.",
    categorySlug: "css-ui",
    categoryName: "CSS & UI Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "color-palette-generator",
    popular: true,
    iconName: "Palette",
    gradient: "from-pink-500 to-rose-600",
    tags: ["Palette", "Color", "HEX", "RGB", "HSL"],
  },
  {
    id: "tool-3",
    name: "Add Page Numbers to PDF",
    slug: "pdf-page-numberer",
    tagline: "Upload any PDF document and insert custom page numbers with live positioning, font sizes, and format control.",
    categorySlug: "pdf-tools",
    categoryName: "PDF Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "pdf-page-numberer",
    popular: false,
    iconName: "FileText",
    gradient: "from-indigo-500 to-blue-600",
    tags: ["PDF", "Page Numbers", "Document", "Editor"],
  },
  {
    id: "tool-4",
    name: "AI Flowchart Generator",
    slug: "ai-flowchart-generator",
    tagline: "Describe any process in natural language to generate, edit, zoom, and export flowcharts to PNG, SVG, or Mermaid.",
    categorySlug: "ai-tools",
    categoryName: "Generators & Media",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "ai-flowchart-generator",
    popular: true,
    iconName: "Sparkles",
    gradient: "from-purple-500 to-violet-600",
    tags: ["AI", "Flowchart", "Diagram", "Mermaid"],
  },
  {
    id: "tool-5",
    name: "Audio Converter",
    slug: "audio-converter",
    tagline: "Convert audio files between MP3, WAV, AAC, OGG, FLAC, and M4A with bitrate selection and trim controls.",
    categorySlug: "ai-tools",
    categoryName: "Generators & Media",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "audio-converter",
    popular: false,
    iconName: "Binary",
    gradient: "from-emerald-500 to-teal-600",
    tags: ["Audio", "Converter", "MP3", "WAV", "Sound"],
  },
  {
    id: "tool-6",
    name: "Barcode Generator",
    slug: "barcode-generator",
    tagline: "Generate Code128, EAN13, UPC, CODE39, CODE93, and ISBN barcodes with custom sizes and SVG/PNG download.",
    categorySlug: "css-ui",
    categoryName: "CSS & UI Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "barcode-generator",
    popular: false,
    iconName: "QrCode",
    gradient: "from-orange-500 to-amber-600",
    tags: ["Barcode", "Code128", "EAN13", "UPC", "Vector"],
  },
  {
    id: "tool-7",
    name: "Digital Signature Creator",
    slug: "digital-signature-creator",
    tagline: "Draw smooth digital signatures, type signatures with typography fonts, or upload images with transparent background.",
    categorySlug: "security",
    categoryName: "Security & Crypto",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "digital-signature-creator",
    popular: true,
    iconName: "KeyRound",
    gradient: "from-cyan-500 to-blue-600",
    tags: ["Signature", "Draw", "Digital", "PDF", "Security"],
  },
  {
    id: "tool-8",
    name: "Document Converter",
    slug: "document-converter",
    tagline: "Convert text documents seamlessly between Markdown, HTML, JSON, CSV, TXT, XML, and YAML with live preview.",
    categorySlug: "text-utilities",
    categoryName: "Text & Markdown",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "document-converter",
    popular: false,
    iconName: "Binary",
    gradient: "from-teal-500 to-emerald-600",
    tags: ["Converter", "Markdown", "HTML", "JSON", "CSV"],
  },
  {
    id: "tool-9",
    name: "Favicon Converter",
    slug: "favicon-converter",
    tagline: "Upload any image to generate browser favicons in 16x16 up to 256x256 sizes. Download as ICO, PNG, or ZIP.",
    categorySlug: "image-tools",
    categoryName: "Image & Asset Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "favicon-converter",
    popular: true,
    iconName: "Layers",
    gradient: "from-rose-500 to-red-600",
    tags: ["Favicon", "ICO", "PNG", "App Icon", "Crop"],
  },
  {
    id: "tool-10",
    name: "Image Processor",
    slug: "image-processor",
    tagline: "Resize, crop, rotate, flip, compress, convert formats (JPG, PNG, WEBP, AVIF), and blur backgrounds in browser.",
    categorySlug: "image-tools",
    categoryName: "Image & Asset Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "image-processor",
    popular: true,
    iconName: "Layers",
    gradient: "from-blue-500 to-indigo-600",
    tags: ["Image", "Processor", "Resize", "Crop", "WebP"],
  },
  {
    id: "tool-11",
    name: "ImaGrow Image Editor",
    slug: "imagrow",
    tagline: "Professional image adjustments (brightness, contrast, saturation, hue, blur, sharpen, exposure) with preset filters.",
    categorySlug: "image-tools",
    categoryName: "Image & Asset Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "imagrow",
    popular: true,
    iconName: "Layers",
    gradient: "from-amber-500 to-rose-600",
    tags: ["ImaGrow", "Editor", "Filters", "Adjustments", "Photo"],
  },
  {
    id: "tool-12",
    name: "Invoice Generator",
    slug: "invoice-generator",
    tagline: "Create professional business invoices with company details, logo upload, line items, taxes, and instant PDF print.",
    categorySlug: "ai-tools",
    categoryName: "Generators & Media",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "invoice-generator",
    popular: true,
    iconName: "Sparkles",
    gradient: "from-orange-500 to-amber-600",
    tags: ["Invoice", "PDF", "Business", "Tax", "Billing"],
  },
  {
    id: "tool-13",
    name: "JSON Formatter & Validator",
    slug: "json-formatter",
    tagline: "Format, validate, beautify, tree view inspect, and minify complex JSON payloads with error line highlighting.",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "json-formatter",
    popular: true,
    iconName: "Braces",
    gradient: "from-sky-500 to-blue-600",
    tags: ["Formatter", "JSON", "Minifier", "Dev", "Tree"],
  },
  {
    id: "tool-14",
    name: "Lorem Ipsum Generator",
    slug: "lorem-ipsum-generator",
    tagline: "Generate customized placeholder text by paragraphs, words, sentences, or lists with optional HTML tags.",
    categorySlug: "text-utilities",
    categoryName: "Text & Markdown",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "lorem-ipsum-generator",
    popular: false,
    iconName: "Binary",
    gradient: "from-emerald-500 to-teal-600",
    tags: ["Lorem", "Ipsum", "Placeholder", "Text", "HTML"],
  },
  {
    id: "tool-15",
    name: "Markdown Editor & Live Preview",
    slug: "markdown-editor",
    tagline: "Live split-view Markdown editor with syntax highlighting, word count, dark mode, and HTML/PDF export.",
    categorySlug: "text-utilities",
    categoryName: "Text & Markdown",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "markdown-editor",
    popular: true,
    iconName: "Binary",
    gradient: "from-indigo-500 to-violet-600",
    tags: ["Markdown", "Editor", "Preview", "Export", "HTML"],
  },
  {
    id: "tool-16",
    name: "Cryptographic Password Generator",
    slug: "password-generator",
    tagline: "Generate cryptographically secure passwords with custom length, character sets, entropy score, and history log.",
    categorySlug: "security",
    categoryName: "Security & Crypto",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "password-generator",
    popular: true,
    iconName: "KeyRound",
    gradient: "from-emerald-500 to-teal-600",
    tags: ["Password", "Security", "Crypto", "Generator"],
  },
  {
    id: "tool-17",
    name: "PDF Compressor",
    slug: "pdf-compressor",
    tagline: "Compress PDF documents in browser to reduce file size while preserving document quality and formatting.",
    categorySlug: "pdf-tools",
    categoryName: "PDF Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "pdf-compressor",
    popular: true,
    iconName: "FileText",
    gradient: "from-blue-500 to-cyan-600",
    tags: ["PDF", "Compress", "Optimize", "Size", "Document"],
  },
  {
    id: "tool-18",
    name: "PDF Merger",
    slug: "pdf-merger",
    tagline: "Combine multiple PDF documents into a single file with drag & drop page reordering and page removal.",
    categorySlug: "pdf-tools",
    categoryName: "PDF Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "pdf-merger",
    popular: true,
    iconName: "FileText",
    gradient: "from-violet-500 to-purple-600",
    tags: ["PDF", "Merge", "Combine", "Reorder", "Document"],
  },
  {
    id: "tool-19",
    name: "PDF Splitter",
    slug: "pdf-splitter",
    tagline: "Split PDF pages into separate files, extract page ranges, or download extracted pages in bulk.",
    categorySlug: "pdf-tools",
    categoryName: "PDF Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "pdf-splitter",
    popular: false,
    iconName: "FileText",
    gradient: "from-rose-500 to-pink-600",
    tags: ["PDF", "Split", "Extract", "Pages", "Document"],
  },
  {
    id: "tool-20",
    name: "PDF to Multiple Pages (N-Up Grid)",
    slug: "pdf-multiple-pages",
    tagline: "Arrange PDF pages into 2-up, 4-up, 6-up, or 8-up grid sheets for paper saving and presentation handouts.",
    categorySlug: "pdf-tools",
    categoryName: "PDF Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "pdf-multiple-pages",
    popular: false,
    iconName: "FileText",
    gradient: "from-amber-500 to-orange-600",
    tags: ["PDF", "Grid", "N-Up", "Print", "Layout"],
  },
  {
    id: "tool-21",
    name: "QR Code Generator",
    slug: "qr-generator",
    tagline: "Create high-resolution vector SVG/PNG QR codes for URLs, WiFi, Contact vCards, text, and phone numbers.",
    categorySlug: "css-ui",
    categoryName: "CSS & UI Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "qr-generator",
    popular: true,
    iconName: "QrCode",
    gradient: "from-amber-500 to-orange-600",
    tags: ["QR Code", "Vector", "SVG", "WiFi", "vCard"],
  },
  {
    id: "tool-22",
    name: "SVG Editor & Code Optimizer",
    slug: "svg-editor",
    tagline: "Upload or paste SVG code to edit paths, adjust fills and stroke properties, optimize markup, and export PNG/SVG.",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "svg-editor",
    popular: false,
    iconName: "Braces",
    gradient: "from-indigo-500 to-blue-600",
    tags: ["SVG", "Editor", "Paths", "Optimize", "Dev"],
  },
  {
    id: "tool-23",
    name: "Text Formatter & Case Converter",
    slug: "text-formatter",
    tagline: "Uppercase, Lowercase, Title Case, Sentence Case, line sorting, duplicate line removal, and character/word metrics.",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "text-formatter",
    popular: false,
    iconName: "Braces",
    gradient: "from-teal-500 to-cyan-600",
    tags: ["Text", "Case", "Format", "Sort", "Duplicates"],
  },
  {
    id: "tool-24",
    name: "Video to GIF Converter",
    slug: "video-gif-converter",
    tagline: "Convert MP4, WEBM, and MOV videos into optimized animated GIFs with timeline trimming, FPS, and resolution control.",
    categorySlug: "image-tools",
    categoryName: "Image & Asset Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "video-gif-converter",
    popular: true,
    iconName: "Layers",
    gradient: "from-fuchsia-500 to-pink-600",
    tags: ["Video", "GIF", "MP4", "Trim", "Animation"],
  },
];

export const WHY_TOOLVERSE: ValueProp[] = [
  {
    id: "prop-1",
    title: "100% Privacy & Client-Side Execution",
    description: "Your data stays in your browser. All computations happen locally with Web APIs so your code, images, and text never touch external servers.",
    iconName: "Shield",
    badge: "Privacy First",
  },
  {
    id: "prop-2",
    title: "Blazing Fast & Lightweight",
    description: "Built on Next.js 16 App Router and React 19 for instant page loads, zero bloat, and sub-millisecond execution.",
    iconName: "Cpu",
    badge: "High Performance",
  },
  {
    id: "prop-3",
    title: "Zero Ads & No Account Required",
    description: "No annoying banner ads, no cookie popups, and no sign-up paywalls. Jump straight in and get your work done.",
    iconName: "Sparkle",
    badge: "Clean DX",
  },
  {
    id: "prop-4",
    title: "Developer-First Experience",
    description: "Keyboard shortcuts, command palette (⌘K), favorites bookmarking, and dark mode default built for speed.",
    iconName: "Terminal",
    badge: "Built for Creators",
  },
];
