import { Category, FeaturedTool, ValueProp } from "@/types";

export const ROADMAP_CATEGORIES: Category[] = [
  {
    id: "cat-9",
    name: "AI Developer Tools",
    slug: "ai-developer-tools",
    description: "Production-ready AI utilities: English to Regex, Conventional Commit messages, and Code Explainer.",
    iconName: "Sparkles",
    color: "from-zinc-800 to-zinc-900 text-orange-400 border-zinc-700/60",
    toolCount: 1,
  },
  {
    id: "cat-1",
    name: "Developer Tools",
    slug: "developer-tools",
    description: "Formatters, decoders, minifiers, SVG tools, and essential coding utilities.",
    iconName: "Code2",
    color: "from-zinc-800 to-zinc-900 text-sky-400 border-zinc-700/60",
    toolCount: 3,
  },
  {
    id: "cat-2",
    name: "Security & Crypto",
    slug: "security",
    description: "Strong password generators, digital signature tools, and token validators.",
    iconName: "ShieldCheck",
    color: "from-zinc-800 to-zinc-900 text-emerald-400 border-zinc-700/60",
    toolCount: 2,
  },
  {
    id: "cat-3",
    name: "Text & Markdown",
    slug: "text-utilities",
    description: "Markdown editors, document converters, Base64 encoders, and text formatters.",
    iconName: "Binary",
    color: "from-zinc-800 to-zinc-900 text-violet-400 border-zinc-700/60",
    toolCount: 3,
  },
  {
    id: "cat-4",
    name: "CSS & UI Utilities",
    slug: "css-ui",
    description: "QR code generators, barcode generators, color palettes, and SVG icon suites.",
    iconName: "Palette",
    color: "from-zinc-800 to-zinc-900 text-amber-400 border-zinc-700/60",
    toolCount: 4,
  },
  {
    id: "cat-5",
    name: "Image & Asset Tools",
    slug: "image-tools",
    description: "ImaGrow image editor, image processor, favicon converter, and video to GIF.",
    iconName: "Image",
    color: "from-zinc-800 to-zinc-900 text-rose-400 border-zinc-700/60",
    toolCount: 4,
  },
  {
    id: "cat-6",
    name: "PDF Utilities",
    slug: "pdf-tools",
    description: "Merge, split, compress, page numberer, and N-up grid page layout.",
    iconName: "FileText",
    color: "from-zinc-800 to-zinc-900 text-indigo-400 border-zinc-700/60",
    toolCount: 5,
  },
  {
    id: "cat-7",
    name: "Generators & Media",
    slug: "ai-tools",
    description: "AI Flowchart generator, invoice builder, and audio format converter.",
    iconName: "Sparkles",
    color: "from-zinc-800 to-zinc-900 text-teal-400 border-zinc-700/60",
    toolCount: 3,
  },
  {
    id: "cat-8",
    name: "Web Utilities",
    slug: "web-utilities",
    description: "URL shorteners, link management, custom aliases, and Web QR generator tools.",
    iconName: "Link",
    color: "from-zinc-800 to-zinc-900 text-orange-400 border-zinc-700/60",
    toolCount: 1,
  },
];

export const FEATURED_TOOLS: FeaturedTool[] = [
  // --- AI Developer Tools ---
  {
    id: "tool-26",
    name: "AI Regex Generator",
    slug: "ai-regex-generator",
    tagline: "Convert plain English into regular expressions with part-by-part explanations and live test playground.",
    categorySlug: "ai-developer-tools",
    categoryName: "AI Developer Tools",
    badgeText: "AI Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "ai-regex-generator",
    popular: true,
    iconName: "Braces",
    gradient: "from-orange-500 to-amber-600",
    tags: ["AI", "Regex", "Pattern", "Validation", "Dev"],
  },

  // --- Existing Utilities ---
  {
    id: "tool-1",
    name: "SVG Icons Library",
    slug: "svg-icons-library",
    tagline: "Searchable SVG icon library with instant search, pack filters, stroke/color customization, and JSX/React copy.",
    categorySlug: "css-ui",
    categoryName: "CSS & UI Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "svg-icons-library",
    popular: true,
    iconName: "Palette",
    gradient: "from-amber-500 to-orange-600",
    tags: ["Icons", "SVG", "JSX", "React", "UI"],
  },
  {
    id: "tool-2",
    name: "Color Palette Generator",
    slug: "color-palette-generator",
    tagline: "Generate and browse color palettes with harmony modes (monochrome, triadic, complementary) and contrast checker.",
    categorySlug: "css-ui",
    categoryName: "CSS & UI Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "color-palette-generator",
    popular: true,
    iconName: "Palette",
    gradient: "from-orange-500 to-rose-600",
    tags: ["Color", "Palette", "Design", "CSS", "UI"],
  },
  {
    id: "tool-3",
    name: "AI Flowchart Generator",
    slug: "ai-flowchart-generator",
    tagline: "Turn text ideas into interactive Mermaid.js flowcharts with live visual rendering and SVG export.",
    categorySlug: "ai-tools",
    categoryName: "Generators & Media",
    badgeText: "AI Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "ai-flowchart-generator",
    popular: true,
    iconName: "Braces",
    gradient: "from-amber-500 to-orange-600",
    tags: ["AI", "Flowchart", "Diagram", "Mermaid", "Export"],
  },
  {
    id: "tool-4",
    name: "OG Image Generator",
    slug: "og-image-generator",
    tagline: "Create social card visual previews for blog posts and websites with live browser preview.",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "og-image-generator",
    popular: false,
    iconName: "Palette",
    gradient: "from-orange-500 to-amber-600",
    tags: ["OG Image", "Meta", "Social", "SEO"],
  },
  {
    id: "tool-5",
    name: "Image Processor",
    slug: "image-processor",
    tagline: "Batch resize, crop, rotate, and convert web images with browser-based WebGL acceleration.",
    categorySlug: "image-tools",
    categoryName: "Image & Asset Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "image-processor",
    popular: true,
    iconName: "Binary",
    gradient: "from-amber-500 to-orange-600",
    tags: ["Image", "Resize", "Crop", "Batch", "WebGL"],
  },
  {
    id: "tool-6",
    name: "ImaGrow",
    slug: "imagrow",
    tagline: "Upscale and enhance image resolution with smart bicubic canvas processing.",
    categorySlug: "image-tools",
    categoryName: "Image & Asset Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "imagrow",
    popular: false,
    iconName: "Binary",
    gradient: "from-orange-500 to-rose-600",
    tags: ["Upscale", "Image", "Enhance", "Resolution"],
  },
  {
    id: "tool-7",
    name: "Favicon Converter",
    slug: "favicon-converter",
    tagline: "Convert any PNG, SVG, or JPG image into multi-resolution ICO, Apple Touch, and Android Web App icons.",
    categorySlug: "image-tools",
    categoryName: "Image & Asset Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "favicon-converter",
    popular: false,
    iconName: "Binary",
    gradient: "from-amber-500 to-orange-600",
    tags: ["Favicon", "ICO", "Web App", "Icons"],
  },
  {
    id: "tool-8",
    name: "Add Page Numbers to PDF",
    slug: "pdf-page-numberer",
    tagline: "Upload any PDF document and insert custom page numbers with positioning, margins, and font styles.",
    categorySlug: "pdf-tools",
    categoryName: "PDF Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "pdf-page-numberer",
    popular: true,
    iconName: "Braces",
    gradient: "from-orange-500 to-rose-600",
    tags: ["PDF", "Page Numbers", "Pagination", "Documents"],
  },
  {
    id: "tool-9",
    name: "PDF Compressor",
    slug: "pdf-compressor",
    tagline: "Reduce PDF file sizes while preserving vector text and image quality.",
    categorySlug: "pdf-tools",
    categoryName: "PDF Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "pdf-compressor",
    popular: true,
    iconName: "Braces",
    gradient: "from-amber-500 to-orange-600",
    tags: ["PDF", "Compress", "Optimize", "File Size"],
  },
  {
    id: "tool-10",
    name: "PDF Merger",
    slug: "pdf-merger",
    tagline: "Combine multiple PDF documents into a single organized file with drag-and-drop reordering.",
    categorySlug: "pdf-tools",
    categoryName: "PDF Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "pdf-merger",
    popular: false,
    iconName: "Layers",
    gradient: "from-orange-500 to-amber-600",
    tags: ["PDF", "Merge", "Combine", "Reorder"],
  },
  {
    id: "tool-11",
    name: "PDF Splitter",
    slug: "pdf-splitter",
    tagline: "Extract custom page ranges or split PDF files into individual pages.",
    categorySlug: "pdf-tools",
    categoryName: "PDF Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "pdf-splitter",
    popular: false,
    iconName: "Braces",
    gradient: "from-amber-500 to-orange-600",
    tags: ["PDF", "Split", "Extract", "Pages"],
  },
  {
    id: "tool-12",
    name: "PDF to Multiple Pages",
    slug: "pdf-multiple-pages",
    tagline: "Layout multiple PDF pages onto a single sheet (2-up, 4-up grid) for printing and slides.",
    categorySlug: "pdf-tools",
    categoryName: "PDF Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "pdf-multiple-pages",
    popular: false,
    iconName: "Layers",
    gradient: "from-orange-500 to-rose-600",
    tags: ["PDF", "Grid", "Print", "Layout"],
  },
  {
    id: "tool-13",
    name: "JSON Formatter",
    slug: "json-formatter",
    tagline: "Format, validate, beautify, and minify JSON with syntax highlighting and tree inspection.",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "json-formatter",
    popular: true,
    iconName: "Braces",
    gradient: "from-amber-500 to-orange-600",
    tags: ["JSON", "Formatter", "Beautifier", "Syntax"],
  },
  {
    id: "tool-14",
    name: "Markdown Editor",
    slug: "markdown-editor",
    tagline: "Live split-pane Markdown editor with real-time preview, table support, and HTML export.",
    categorySlug: "text-utilities",
    categoryName: "Text & Markdown",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "markdown-editor",
    popular: false,
    iconName: "Binary",
    gradient: "from-orange-500 to-rose-600",
    tags: ["Markdown", "Editor", "Preview", "HTML"],
  },
  {
    id: "tool-15",
    name: "SVG Editor",
    slug: "svg-editor",
    tagline: "Inspect, clean, optimize, and edit raw SVG markup with live canvas preview.",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "svg-editor",
    popular: false,
    iconName: "Palette",
    gradient: "from-amber-500 to-orange-600",
    tags: ["SVG", "Editor", "Clean", "Vector"],
  },
  {
    id: "tool-16",
    name: "Text Formatter",
    slug: "text-formatter",
    tagline: "Convert string case (camelCase, snake_case, Title Case), clean whitespace, and count words.",
    categorySlug: "text-utilities",
    categoryName: "Text & Markdown",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "text-formatter",
    popular: false,
    iconName: "Binary",
    gradient: "from-orange-500 to-amber-600",
    tags: ["Text", "Case", "String", "Word Count"],
  },
  {
    id: "tool-17",
    name: "Audio Converter",
    slug: "audio-converter",
    tagline: "Convert MP3, WAV, OGG, and AAC audio files with bit-rate controls.",
    categorySlug: "ai-tools",
    categoryName: "Generators & Media",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "audio-converter",
    popular: false,
    iconName: "Binary",
    gradient: "from-amber-500 to-orange-600",
    tags: ["Audio", "MP3", "WAV", "Converter"],
  },
  {
    id: "tool-18",
    name: "Document Converter",
    slug: "document-converter",
    tagline: "Convert TXT, HTML, Markdown, and CSV document formats.",
    categorySlug: "text-utilities",
    categoryName: "Text & Markdown",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "document-converter",
    popular: false,
    iconName: "Binary",
    gradient: "from-orange-500 to-rose-600",
    tags: ["Document", "CSV", "HTML", "TXT"],
  },
  {
    id: "tool-19",
    name: "Video to GIF Converter",
    slug: "video-gif-converter",
    tagline: "Convert MP4 / WebM video clips into animated GIFs with custom FPS and dimensions.",
    categorySlug: "image-tools",
    categoryName: "Image & Asset Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "video-gif-converter",
    popular: false,
    iconName: "Binary",
    gradient: "from-amber-500 to-orange-600",
    tags: ["Video", "GIF", "MP4", "Animation"],
  },
  {
    id: "tool-20",
    name: "Invoice Generator",
    slug: "invoice-generator",
    tagline: "Generate professional client invoices with tax calculations, items, and PDF download.",
    categorySlug: "ai-tools",
    categoryName: "Generators & Media",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "invoice-generator",
    popular: true,
    iconName: "KeyRound",
    gradient: "from-orange-500 to-amber-600",
    tags: ["Invoice", "PDF", "Billing", "Business"],
  },
  {
    id: "tool-21",
    name: "Lorem Ipsum Generator",
    slug: "lorem-ipsum-generator",
    tagline: "Generate placeholder text, paragraphs, sentences, and HTML lists.",
    categorySlug: "text-utilities",
    categoryName: "Text & Markdown",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "lorem-ipsum-generator",
    popular: false,
    iconName: "Binary",
    gradient: "from-amber-500 to-orange-600",
    tags: ["Lorem Ipsum", "Text", "Placeholder"],
  },
  {
    id: "tool-22",
    name: "Password Generator",
    slug: "password-generator",
    tagline: "Generate strong, secure passwords with custom entropy, symbols, and length controls.",
    categorySlug: "security",
    categoryName: "Security & Crypto",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "password-generator",
    popular: true,
    iconName: "KeyRound",
    gradient: "from-orange-500 to-rose-600",
    tags: ["Password", "Security", "Crypto", "Generator"],
  },
  {
    id: "tool-23",
    name: "QR Code Generator",
    slug: "qr-generator",
    tagline: "Create styled vector QR codes for URLs, Wi-Fi passwords, and contact VCards with logo upload.",
    categorySlug: "css-ui",
    categoryName: "CSS & UI Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "qr-generator",
    popular: true,
    iconName: "QrCode",
    gradient: "from-amber-500 to-orange-600",
    tags: ["QR Code", "Vector", "Wi-Fi", "VCard"],
  },
  {
    id: "tool-24",
    name: "Barcode Generator",
    slug: "barcode-generator",
    tagline: "Generate 1D & 2D barcodes (CODE128, EAN-13, UPC, CODE39) with custom dimensions.",
    categorySlug: "css-ui",
    categoryName: "CSS & UI Utilities",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "barcode-generator",
    popular: false,
    iconName: "Lock",
    gradient: "from-orange-500 to-amber-600",
    tags: ["Barcode", "EAN-13", "UPC", "CODE128"],
  },
  {
    id: "tool-25",
    name: "URL Shortener",
    slug: "url-shortener",
    tagline: "Create, manage, and share shortened links with custom aliases, expiration dates, click analytics, and instant QR generation.",
    categorySlug: "web-utilities",
    categoryName: "Web Utilities",
    badgeText: "New Feature",
    isComingSoon: false,
    isLive: true,
    actionKey: "url-shortener",
    popular: true,
    iconName: "Link",
    gradient: "from-orange-500 to-amber-600",
    tags: ["URL Shortener", "Links", "Analytics", "Custom Alias", "QR Code"],
  },
];

export const VALUE_PROPS: ValueProp[] = [
  {
    id: "vp-1",
    title: "26 In-Browser Utilities",
    description: "PDF tools, AI developer utilities, image processors, QR generators, and formatters in one clean SaaS suite.",
    iconName: "Zap",
    badge: "Expanded Suite",
  },
  {
    id: "vp-2",
    title: "100% Client & AI Enabled",
    description: "Zero external tracking. Your code and files are processed securely in your browser and AI engines.",
    iconName: "ShieldCheck",
    badge: "Privacy First",
  },
  {
    id: "vp-3",
    title: "Sub-ms Execution Speed",
    description: "Built on WebGL and WebAssembly for instantaneous feedback without server bottlenecks.",
    iconName: "Cpu",
    badge: "Ultra Fast",
  },
];

export const WHY_TOOLVERSE = VALUE_PROPS;
