import { Category, FeaturedTool, ValueProp } from "@/types";

export const ROADMAP_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Developer Tools",
    slug: "developer-tools",
    description: "Formatters, decoders, minifiers, and essential coding utilities.",
    iconName: "Code2",
    color: "from-zinc-800 to-zinc-900 text-sky-400 border-zinc-700/60",
    toolCount: 6,
  },
  {
    id: "cat-2",
    name: "Security & Crypto",
    slug: "security",
    description: "Strong password generators, JWT decoders, hash checkers, and token validators.",
    iconName: "ShieldCheck",
    color: "from-zinc-800 to-zinc-900 text-emerald-400 border-zinc-700/60",
    toolCount: 4,
  },
  {
    id: "cat-3",
    name: "Text & Markdown",
    slug: "text-utilities",
    description: "Case converters, Base64 encoders, word counters, and diff checkers.",
    iconName: "Binary",
    color: "from-zinc-800 to-zinc-900 text-violet-400 border-zinc-700/60",
    toolCount: 4,
  },
  {
    id: "cat-4",
    name: "CSS & UI Utilities",
    slug: "css-ui",
    description: "QR code generators, box-shadow creators, glassmorphism CSS, and icons.",
    iconName: "Palette",
    color: "from-zinc-800 to-zinc-900 text-amber-400 border-zinc-700/60",
    toolCount: 3,
  },
  {
    id: "cat-5",
    name: "Image & Asset Tools",
    slug: "image-tools",
    description: "Compress, convert, resize, and crop images directly in-browser.",
    iconName: "Image",
    color: "from-zinc-800 to-zinc-900 text-rose-400 border-zinc-700/60",
    toolCount: 3,
  },
  {
    id: "cat-6",
    name: "PDF Utilities",
    slug: "pdf-tools",
    description: "Merge, split, extract pages, and optimize document sizes.",
    iconName: "FileText",
    color: "from-zinc-800 to-zinc-900 text-indigo-400 border-zinc-700/60",
    toolCount: 2,
  },
  {
    id: "cat-7",
    name: "AI & Content Tools",
    slug: "ai-tools",
    description: "Prompt helpers, token counters, and local browser AI workflows.",
    iconName: "Sparkles",
    color: "from-zinc-800 to-zinc-900 text-teal-400 border-zinc-700/60",
    toolCount: 3,
  },
  {
    id: "cat-8",
    name: "Productivity",
    slug: "productivity",
    description: "Pomodoro timers, daily task scratchpads, and focus tools.",
    iconName: "Zap",
    color: "from-zinc-800 to-zinc-900 text-yellow-400 border-zinc-700/60",
    toolCount: 2,
  },
];

export const FEATURED_TOOLS: FeaturedTool[] = [
  {
    id: "tool-1",
    name: "JSON Formatter & Validator",
    tagline: "Format, validate, beautify, and minify complex JSON payloads with instant error highlighting.",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "json-formatter",
    popular: true,
    iconName: "Braces",
    gradient: "from-sky-500 to-blue-600",
    tags: ["Formatter", "JSON", "Minifier", "Dev"],
  },
  {
    id: "tool-2",
    name: "Cryptographic Password Generator",
    tagline: "Generate cryptographically secure passwords and passphrases with real-time strength meter.",
    categorySlug: "security",
    categoryName: "Security & Crypto",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "password-generator",
    popular: true,
    iconName: "KeyRound",
    gradient: "from-emerald-500 to-teal-600",
    tags: ["Password", "Security", "Crypto", "Generator"],
  },
  {
    id: "tool-3",
    name: "QR Code Generator",
    tagline: "Create high-resolution vector SVG/PNG QR codes instantly from text, URLs, or Wi-Fi credentials.",
    categorySlug: "css-ui",
    categoryName: "CSS & UI",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "qr-generator",
    popular: true,
    iconName: "QrCode",
    gradient: "from-amber-500 to-orange-600",
    tags: ["QR Code", "Vector", "SVG", "Generator"],
  },
  {
    id: "tool-4",
    name: "JWT Inspector & Decoder",
    tagline: "Decode Header, Payload, and verify expiration dates for JSON Web Tokens client-side.",
    categorySlug: "developer-tools",
    categoryName: "Developer Tools",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "jwt-decoder",
    popular: true,
    iconName: "Lock",
    gradient: "from-indigo-500 to-purple-600",
    tags: ["JWT", "Auth", "Decoder", "Token"],
  },
  {
    id: "tool-5",
    name: "Base64 Encoder & Decoder",
    tagline: "Convert plain text to Base64 and decode Base64 strings with UTF-8 support instantly.",
    categorySlug: "text-utilities",
    categoryName: "Text & Markdown",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "base64-tool",
    popular: false,
    iconName: "Binary",
    gradient: "from-violet-500 to-fuchsia-600",
    tags: ["Base64", "Encode", "Decode", "Text"],
  },
  {
    id: "tool-6",
    name: "Text Converter & Word Counter",
    tagline: "Convert case (UPPERCASE, lowercase, Title Case, camelCase) and analyze word/character metrics.",
    categorySlug: "text-utilities",
    categoryName: "Text & Markdown",
    badgeText: "Live Tool",
    isComingSoon: false,
    isLive: true,
    actionKey: "text-converter",
    popular: false,
    iconName: "Binary",
    gradient: "from-teal-500 to-cyan-600",
    tags: ["Case", "Converter", "Word Count", "Text"],
  },
  {
    id: "tool-7",
    name: "Client Image Compressor",
    tagline: "Compress WebP, PNG, and JPG images up to 80% without losing visual fidelity.",
    categorySlug: "image-tools",
    categoryName: "Image & Asset Tools",
    badgeText: "Coming Soon",
    isComingSoon: true,
    isLive: false,
    iconName: "Layers",
    gradient: "from-rose-500 to-pink-600",
    tags: ["Image", "Compressor", "WebP", "Optimization"],
  },
  {
    id: "tool-8",
    name: "CSS Glassmorphism & Shadow Generator",
    tagline: "Design modern box-shadows and glass visual effects with 1-click CSS code export.",
    categorySlug: "css-ui",
    categoryName: "CSS & UI",
    badgeText: "Coming Soon",
    isComingSoon: true,
    isLive: false,
    iconName: "Palette",
    gradient: "from-purple-500 to-indigo-600",
    tags: ["CSS", "Shadow", "UI", "Design"],
  },
];

export const WHY_TOOLVERSE: ValueProp[] = [
  {
    id: "prop-1",
    title: "100% Privacy & Client-Side Execution",
    description: "Your data stays in your browser. All computations happen locally with Web APIs so your code, images, and text never touch external servers.",
    iconName: "Shield",
    badge: "Privacy First",
  },
  {
    id: "prop-2",
    title: "Blazing Fast & Lightweight",
    description: "Built on Next.js 16 App Router and React 19 for instant page loads, zero bloat, and sub-millisecond execution.",
    iconName: "Cpu",
    badge: "High Performance",
  },
  {
    id: "prop-3",
    title: "Zero Ads & No Account Required",
    description: "No annoying banner ads, no cookie popups, and no sign-up paywalls. Jump straight in and get your work done.",
    iconName: "Sparkle",
    badge: "Clean DX",
  },
  {
    id: "prop-4",
    title: "Developer-First Experience",
    description: "Keyboard shortcuts, command palette (⌘K), favorites bookmarking, and dark mode default built for speed.",
    iconName: "Terminal",
    badge: "Built for Creators",
  },
];
