import { LogRule } from "./types";

export const LOG_RULES: LogRule[] = [
  {
    id: "ECONNREFUSED",
    name: "Connection Refused (ECONNREFUSED)",
    patterns: [
      "ECONNREFUSED",
      /connection refused/i,
      /failed to connect to/i,
      /could not connect/i,
    ],
    summary: "The application tried to connect to a service, but the connection was refused.",
    cause: "The target service may not be running or the host/port may be incorrect.",
    checks: [
      "Confirm whether the target service is running",
      "Verify the host address and port number in configuration",
      "Check firewall, network policies, or security groups",
    ],
  },
  {
    id: "ECONNRESET",
    name: "Connection Reset (ECONNRESET)",
    patterns: [
      "ECONNRESET",
      /connection reset by peer/i,
      /socket hang up/i,
    ],
    summary: "The network connection was forcibly closed by the remote peer.",
    cause: "The target server crashed, restarted, or closed the socket connection unexpectedly.",
    checks: [
      "Inspect the target server crash and application logs",
      "Check for intermediate network proxy or load balancer timeouts",
      "Verify socket keep-alive and idle timeout settings",
    ],
  },
  {
    id: "ETIMEDOUT",
    name: "Connection Timed Out (ETIMEDOUT)",
    patterns: [
      "ETIMEDOUT",
      /connection timed out/i,
      /request timed out/i,
      /operation timed out/i,
    ],
    summary: "The connection attempt took too long and timed out.",
    cause: "The target server may be unreachable, overloaded, or responding too slowly.",
    checks: [
      "Verify network connectivity between client and target host",
      "Check the target server CPU, memory, and status",
      "Verify timeout configuration limits in your client code",
    ],
  },
  {
    id: "ENOTFOUND",
    name: "DNS Resolution Failed (ENOTFOUND)",
    patterns: [
      "ENOTFOUND",
      /getaddrinfo ENOTFOUND/i,
      /hostname not found/i,
      /could not resolve host/i,
    ],
    summary: "The domain name or hostname could not be resolved to an IP address.",
    cause: "The hostname spelling is incorrect or DNS resolution failed.",
    checks: [
      "Verify the spelling of the hostname in your configuration",
      "Test DNS resolution using nslookup or dig",
      "Check system network and DNS resolver settings",
    ],
  },
  {
    id: "EACCES",
    name: "Permission Denied (EACCES / EPERM)",
    patterns: [
      "EACCES",
      "EPERM",
      /permission denied/i,
      /operation not permitted/i,
      /access denied/i,
    ],
    summary: "The operation was blocked because of insufficient permissions.",
    cause: "The process user does not have permission to read, write, or execute the resource.",
    checks: [
      "Verify file and directory user/group permissions",
      "Check the process user executing the application",
      "Check access rights to the requested resource or port",
    ],
  },
  {
    id: "ENOENT",
    name: "File or Directory Not Found (ENOENT)",
    patterns: [
      "ENOENT",
      /no such file or directory/i,
      /file not found/i,
      /path does not exist/i,
    ],
    summary: "The requested file or directory could not be found.",
    cause: "The path may be incorrect, missing, or the application is running in a different working directory.",
    checks: [
      "Verify the exact file path and file extension",
      "Check whether the file exists at that path",
      "Check the application's current working directory",
    ],
  },
  {
    id: "EADDRINUSE",
    name: "Port Already In Use (EADDRINUSE)",
    patterns: [
      "EADDRINUSE",
      /port already in use/i,
      /address already in use/i,
    ],
    summary: "The application tried to bind to a network port that is already occupied.",
    cause: "Another instance of the server or another process is running on the same port.",
    checks: [
      "Identify the process using the port (e.g. using lsof -i :PORT or netstat)",
      "Terminate the conflicting process or change the application port",
      "Check for lingering background processes from previous runs",
    ],
  },
  {
    id: "HTTP_401",
    name: "HTTP 401 Unauthorized",
    patterns: [
      /HTTP\s*\/?\s*1\.[01]\s*401/i,
      "401 Unauthorized",
      /authentication failure/i,
      /invalid credentials/i,
      /unauthorized access/i,
    ],
    summary: "The server rejected the request because authentication is missing or invalid.",
    cause: "The request token, API key, or authorization header is missing, expired, or malformed.",
    checks: [
      "Verify the Authorization header or API key provided",
      "Check if the access token or session has expired",
      "Confirm user authentication credentials",
    ],
  },
  {
    id: "HTTP_403",
    name: "HTTP 403 Forbidden",
    patterns: [
      /HTTP\s*\/?\s*1\.[01]\s*403/i,
      "403 Forbidden",
      /access forbidden/i,
    ],
    summary: "The server understood the request but refused access.",
    cause: "The authenticated user or token lacks sufficient permissions or scope to access this resource.",
    checks: [
      "Verify user roles, permissions, or API scope limits",
      "Check server IP whitelist or access control rules",
      "Review resource authorization policies",
    ],
  },
  {
    id: "HTTP_404",
    name: "HTTP 404 Not Found",
    patterns: [
      /HTTP\s*\/?\s*1\.[01]\s*404/i,
      "404 Not Found",
      /resource not found/i,
    ],
    summary: "The requested resource or endpoint URL could not be found.",
    cause: "The request route is incorrect or the resource was deleted.",
    checks: [
      "Verify the URL endpoint path and HTTP method (GET, POST, etc.)",
      "Check API routing rules and route definitions",
      "Ensure the requested record exists in the database",
    ],
  },
  {
    id: "HTTP_500",
    name: "HTTP 500 Internal Server Error",
    patterns: [
      /HTTP\s*\/?\s*1\.[01]\s*500/i,
      "500 Internal Server Error",
      /internal server error/i,
      /unhandled exception/i,
    ],
    summary: "The server encountered an internal error while processing the request.",
    cause: "An unhandled exception or crash occurred in the backend application code.",
    checks: [
      "Review server-side error trace and stack trace logs",
      "Check for unhandled exceptions or null pointer references",
      "Verify database transactions and upstream service calls",
    ],
  },
  {
    id: "HTTP_502",
    name: "HTTP 502 Bad Gateway",
    patterns: [
      /HTTP\s*\/?\s*1\.[01]\s*502/i,
      "502 Bad Gateway",
      /bad gateway/i,
    ],
    summary: "The gateway or proxy received an invalid response from the upstream server.",
    cause: "The backend service crashed or returned a malformed response to Nginx/proxy.",
    checks: [
      "Verify the backend application server status",
      "Check reverse proxy error logs (e.g. Nginx/HAProxy)",
      "Ensure backend port matches proxy configuration",
    ],
  },
  {
    id: "HTTP_503",
    name: "HTTP 503 Service Unavailable",
    patterns: [
      /HTTP\s*\/?\s*1\.[01]\s*503/i,
      "503 Service Unavailable",
      /service unavailable/i,
    ],
    summary: "The server is currently unable to handle the request.",
    cause: "The server is overloaded, under maintenance, or backend service pool is exhausted.",
    checks: [
      "Check server CPU, memory utilization, and thread limits",
      "Verify backend service health checks",
      "Increase server capacity or scale resources if traffic spiked",
    ],
  },
  {
    id: "HTTP_504",
    name: "HTTP 504 Gateway Timeout",
    patterns: [
      /HTTP\s*\/?\s*1\.[01]\s*504/i,
      "504 Gateway Timeout",
      /gateway timeout/i,
    ],
    summary: "The gateway or proxy server timed out waiting for the upstream backend.",
    cause: "The backend database query or application logic took too long to respond.",
    checks: [
      "Inspect slow database queries or blocking I/O calls",
      "Check proxy read timeout setting (e.g. proxy_read_timeout)",
      "Monitor backend service execution duration",
    ],
  },
  {
    id: "SYNTAX_ERROR",
    name: "Syntax Error",
    patterns: [
      "SyntaxError",
      /syntax error/i,
      /unexpected token/i,
      /parsing error/i,
    ],
    summary: "The code parser encountered invalid syntax and could not execute.",
    cause: "A missing bracket, parenthesis, comma, quote, or invalid keyword in code.",
    checks: [
      "Inspect the line number mentioned in the error stack trace",
      "Check for unclosed strings, objects, or arrays",
      "Run a linter or compiler check on the target file",
    ],
  },
  {
    id: "INVALID_JSON",
    name: "Invalid JSON",
    patterns: [
      "JSON.parse",
      /invalid json/i,
      /json parse error/i,
      /unexpected end of json/i,
    ],
    summary: "Failed to parse JSON string data.",
    cause: "The input string is not valid JSON (e.g., trailing comma, unquoted keys, single quotes).",
    checks: [
      "Validate the JSON string format",
      "Ensure keys use double quotes (\x22key\x22)",
      "Check for unescaped newlines or control characters",
    ],
  },
  {
    id: "DB_CONN_ERROR",
    name: "Database Connection Error",
    patterns: [
      /database connection error/i,
      /database connection failed/i,
      /db connection failed/i,
      "PrismaClientInitializationError",
      "SequelizeConnectionError",
      "MongoServerSelectionError",
    ],
    summary: "The application failed to establish a connection with the database server.",
    cause: "Invalid database URI, credentials, target host offline, or connection pool exhausted.",
    checks: [
      "Verify database host, port, username, password, and database name",
      "Test database server connectivity using a CLI client",
      "Check database connection pool limits and firewall rules",
    ],
  },
  {
    id: "MODULE_NOT_FOUND",
    name: "Module Not Found",
    patterns: [
      "MODULE_NOT_FOUND",
      /cannot find module/i,
      /module not found/i,
      /failed to resolve module/i,
    ],
    summary: "The application failed to locate or import a required dependency or file module.",
    cause: "The package is not installed or the relative import path is incorrect.",
    checks: [
      "Run npm install or yarn install to install missing packages",
      "Verify relative import paths (./, ../) and file extensions",
      "Check package.json dependencies and tsconfig.json path aliases",
    ],
  },
];
